---
- name: defining target group
  hosts: web-servers
  tasks:
  - name:  testing ping module 
    ping:

  - name: running sample commands 
    command: date

  # - name: Installing some software in target amazon linux machine 
  #   yum: 
  #     name: httpd 
  #     state: present 